name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  compile-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore ./src
      - name: Build
        run: dotnet build ./src --no-restore
      - name: Test
        run: dotnet test ./src --no-build --verbosity normal
      - name: Publish
        run: dotnet publish ./src --configuration Release --no-restore --nologo --output ./published
      - name: "Zip published content"
        uses: papeloto/action-zip@v1
        with:
          files: ./published/
          recursive: true
          dest: artifact.zip
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: api-artifact
          path: artifact.zip

  publish-bicep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bicep-templates
          path: infrastructure/

  infrastructure-incremental-dev:
    needs: publish-bicep
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: bicep-templates
          path: ./infrastructure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_TEST }}
      - name: Azure Create Resource Group
        uses: Azure/cli@1.0.4
        with:
          azcliversion: 2.23.0
          inlineScript: az group create -l westeurope -n ${{ secrets.AZURE_DEV_RESOURCE_GROUP }}
      - name: Deploy Infrastructure
        id: arm
        uses: Azure/cli@1.0.4
        with:
          azcliversion: 2.23.0
          inlineScript: az deployment group create --resource-group ${{ secrets.AZURE_DEV_RESOURCE_GROUP }} --template-file ./infrastructure/main.bicep --mode Incremental

  deploy-api-dev:
    needs: [compile-api, infrastructure-incremental-dev]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: api-artifact
      - name: Get FunctionApp publish profile
        id: publishprofile
        uses: aliencube/publish-profile-actions@v1
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_TEST }}
        with:
          resourceGroupName: ${{ secrets.AZURE_DEV_RESOURCE_GROUP }}
          appName: "f1man-dev-weu-app"
      - name: "Deploy web app"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "f1man-dev-weu-app"
          publish-profile: ${{ steps.publishprofile.outputs.profile }}
          package: "artifact.zip"

      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v1.5
        with:
          url: https://f1man-dev-weu-app.azurewebsites.net/health
          follow-redirect: no
          max-attempts: 3
          retry-delay: 5s

  infrastructure-complete-dev:
    needs: deploy-api-dev

    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: bicep-templates
          path: ./infrastructure

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_TEST }}

      - name: Deploy infrastrucutre
        uses: Azure/cli@1.0.4
        with:
          azcliversion: 2.23.0
          inlineScript: az deployment group create --resource-group ${{ secrets.AZURE_DEV_RESOURCE_GROUP }} --template-file ./infrastructure/main.bicep --mode Complete
