name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  compile-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore ./src
      - name: Build
        run: dotnet build ./src --no-restore
      - name: Test
        run: dotnet test ./src --no-build --verbosity normal
      - name: Publish
        run: dotnet publish ./src --configuration Release --no-restore --nologo --output ./published
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: api-artifact
          path: ./published/

  publish-bicep:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bicep-templates
          path: infrastructure/

  deploy-dev:
    needs: publish-bicep
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_TEST }}

      - name: Azure Create Resource Group
        uses: Azure/cli@1.0.4
        with:
          azcliversion: 2.23.0
          inlineScript: az group create -l westeurope -n ${{ secrets.AZURE_DEV_RESOURCE_GROUP }}

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: bicep-templates
          path: ./infrastructure

      - name: Deploy infrastrucutre
        uses: Azure/cli@1.0.4
        with:
          azcliversion: 2.23.0
          inlineScript: az deployment group create --resource-group ${{ secrets.AZURE_DEV_RESOURCE_GROUP }} --template-file ./ininfrastructure/main.bicep --parameters --parameters ./infrastructure/parameters.dev.json
